name: store_manage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  logger: ^2.6.2
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  encrypted_shared_preferences: ^3.0.1
  intl: ^0.20.2
  auto_route: ^11.1.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.2.3
  flutter_bloc: ^9.1.1
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  photo_manager: ^3.6.1
  toastification: ^3.0.3
  pinput: ^6.0.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  auto_route_generator: ^10.4.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.3

dependency_overrides:
  matcher: 0.12.17
  test_api: 0.7.7


flutter:
  uses-material-design: true
  assets:
    - .env
    # - assets/svg/
    - assets/images/
    - assets/mocks/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
